### ISSUE TITLE
想借鉴一些思路，希望可以允许

### ISSUE THREAD

**Issue by likewen623** [ziofat/Jx3DpsSimulator#1]
您好~
抱歉打扰，我最近在尝试制作另外一款游戏（古剑）的DPS计算器。
预计以输入面板数值、输出DPS统计结果为主，
比较类似早期的万花DPS计算器~
想借鉴一些您coding中的思路，比如：dot duration， random number generation 等。
希望得到允许。

如果做出来了，会在reference中指明。

谢谢大佬~打扰您啦

**Comment by ziofat** [comment]
https://github.com/j3pz/Acacia

推荐参考这个哈。

MIT 协议开源，不需要我允许。

**Comment by likewen623** [comment]
感谢。
